"""Setup.py generated by Quickstart utility"""

# Always prefer setuptools over distutils
from setuptools import setup, find_packages
from codecs import open
from os import path

import os


def package_files(directory):
    paths = []
    for (path, directories, filenames) in os.walk(directory):
        for filename in filenames:
            paths.append(os.path.join('..', path, filename))
    return paths

here = path.abspath(path.dirname(__file__))

with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    long_description = f.read()

setup(
    name='Loc',
    version='1.0',
    description='Lines of code counter',
    long_description=long_description,
    author='Arden Rasmussen',
    license='MIT',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],
    keywords='setuptools development',
    #  packages=find_packages(exclude=['docs', 'tests']),
    packages=['Loc'],
    package_dir={'Loc': 'loc'},
    package_data={'Loc': 'languages.json'},
    entry_points={
        'console_scripts': ['loc = loc.loc:main']
    },)
